### ISSUE TITLE
Question over permissions required when using a GitHub App

### ISSUE THREAD

**Issue by rfennell** [rajbos/github-fork-updater#114]
I think I am missing the obvious, I have been trying to swap a fork of this project from using a PAT to using the GitHub App.

I have created the GitHub App and installed it into Org I have forked this repo into.

When I run the check update action

- It gets a PAT ok
- But when it tries to calling `https://api.github.com/orgs/blackmarble-actions/repos?per_page=100` it errors.

No StatusCode is returned, all it says is the first GET call to list the repos fails

![image](https://github.com/rajbos/github-fork-updater/assets/324718/a815aa10-54ca-4613-91c6-215c41325214)

I am assuming it is just a permissions issues, but the PAT permissions `public_repo*, read:org, read:user, repo:status*, repo_deployment*, workflow, actions: write, content: write, issues:write` don't map one to one to the Git App permissions.

So, can you confirm the permissions you are using for GitHub Apps

**Comment by rajbos** [comment]
There was an issue with the calls being made to GitHub, it seems that they are now stricter in checking a header in the call that was not passed in. I fixed it in #115 and included the necessary scopes for the GitHub App in the readme. 

Please pull in the update and retest 😀.

**Comment by bm-fez** [comment]
I have test this update on my failing instance (and migrated over another demo instance) and it work perfectly.

Thanks for the quick fix, and saving from the rabbit hole I was going down fiddling with permissions
