### ISSUE TITLE
Update-fork workflow fails of the source repo change include a workflow file

### ISSUE THREAD

**Issue by rfennell** [rajbos/github-fork-updater#41]
# The problem

The recent [commit 71caabb](https://github.com/rajbos/github-fork-updater/commit/71caabb1a2e5e8e9148b730936e78c870c37c2e40) in this repo altered the action `.github/workflows/update-workflow.yml ` file

This change was successfully detected and triggered the issue creation mechanism in my forked repo. However, when I add the `update-fork` label and triggered the `update-workflow` action, the action failed. 

The error was that the `PAT_GITHUB` PAT used by the action also needed the `workflow` scope in addition to the values in the documentation `public_repo, read:org, read:user, repo:status, repo_deployment` 

I noted that if you grant the `workflow` scope all the `repo` scope sub items are added

![image](https://user-images.githubusercontent.com/324718/108825797-5c220680-75bb-11eb-80e7-6b268cd9d747.png)

# The Solution
I created a new PAT with the `workflow` scope and the action completed without error.

**Comment by rajbos** [comment]
Oeh, nice find. Weird that this scope is needed as well. Will look into it. The commit link is not working, will try to find the change.

**Comment by rajbos** [comment]
Ah, the scope is needed since the workflow file itself changed! Makes sense, will merge your pull request in, much appreciated!
