### ISSUE TITLE
Need help with gh app

### ISSUE THREAD

**Issue by ramanveerji** [rajbos/github-fork-updater#73]
I am new to this gh app thing. Can you please suggest me what permissions I should chose in gh app so that i can use this fork updater?

**Comment by rajbos** [comment]
See the security config in the [readme](https://github.com/rajbos/github-fork-updater/blob/main/readme.md#security-1).

**Comment by ramanveerji** [comment]
> See the security config in the [readme](https://github.com/rajbos/github-fork-updater/blob/main/readme.md#security-1).

Yes done.

**Comment by rajbos** [comment]
Closing this issue as I think it now works for you.
